/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the RateLimitEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitEntry{}

// RateLimitEntry struct for RateLimitEntry
type RateLimitEntry struct {
	// Limit value (count for request/token, amount for cost)
	Limit float32 `json:"limit"`
	// Reset window duration
	ResetDuration int32 `json:"resetDuration"`
	// Reset window time unit
	ResetUnit string `json:"resetUnit"`
}

// NewRateLimitEntry instantiates a new RateLimitEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitEntry(limit float32, resetDuration int32, resetUnit string) *RateLimitEntry {
	this := RateLimitEntry{}
	this.Limit = limit
	this.ResetDuration = resetDuration
	this.ResetUnit = resetUnit
	return &this
}

// NewRateLimitEntryWithDefaults instantiates a new RateLimitEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitEntryWithDefaults() *RateLimitEntry {
	this := RateLimitEntry{}
	return &this
}

// GetLimit returns the Limit field value
func (o *RateLimitEntry) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *RateLimitEntry) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *RateLimitEntry) SetLimit(v float32) {
	o.Limit = v
}

// GetResetDuration returns the ResetDuration field value
func (o *RateLimitEntry) GetResetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ResetDuration
}

// GetResetDurationOk returns a tuple with the ResetDuration field value
// and a boolean to check if the value has been set.
func (o *RateLimitEntry) GetResetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetDuration, true
}

// SetResetDuration sets field value
func (o *RateLimitEntry) SetResetDuration(v int32) {
	o.ResetDuration = v
}

// GetResetUnit returns the ResetUnit field value
func (o *RateLimitEntry) GetResetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResetUnit
}

// GetResetUnitOk returns a tuple with the ResetUnit field value
// and a boolean to check if the value has been set.
func (o *RateLimitEntry) GetResetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetUnit, true
}

// SetResetUnit sets field value
func (o *RateLimitEntry) SetResetUnit(v string) {
	o.ResetUnit = v
}

func (o RateLimitEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["resetDuration"] = o.ResetDuration
	toSerialize["resetUnit"] = o.ResetUnit
	return toSerialize, nil
}

type NullableRateLimitEntry struct {
	value *RateLimitEntry
	isSet bool
}

func (v NullableRateLimitEntry) Get() *RateLimitEntry {
	return v.value
}

func (v *NullableRateLimitEntry) Set(val *RateLimitEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitEntry(val *RateLimitEntry) *NullableRateLimitEntry {
	return &NullableRateLimitEntry{value: val, isSet: true}
}

func (v NullableRateLimitEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
